name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker://pandoc/core:3.5
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=what-is-data.pptx
            what-is-data.md
      - uses: actions/upload-artifact@v4
        with:
          name: what-is-data.md
          path: introduction/what-is-data.md