name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - run: iconv -f latin1 -t UTF-8 concept-measurement-data.png > concept-measurement-data.png
      - uses: actions/checkout@v3
      - uses: docker://pandoc/core:3.5
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=what-is-data.pptx
            introduction/img/concept-measurement-data.png
            introduction/what-is-data.md
      - uses: actions/upload-artifact@v4
        with:
          name: what-is-data.pptx
          path: what-is-data.pptx