name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/core:3.5
        working-directory: ./introduction
        with:
          args: >-  # allows you to break string into multiple lines 
            --standalone
            --reference-doc=templates/closer-reference.pptx
            --output=what-is-data.pptx
            introduction/what-is-data.md
      - uses: actions/upload-artifact@v4
        with:
          name: what-is-data.pptx
          path: what-is-data.pptx